### PR TITLE
Added a Makefile

### PR DESCRIPTION
**Pull request by exorcist-git**

### CODE REVIEW

**Comment by exorcist-git** [comment]
i cant contribute to rust code cuz im dumb so i just added a makefile... :)

**Comment by grufwub** [comment]
The makefile is cool, thank you! Though the build script changes you've made are broken. Honestly, with a makefile I wouldn't bother keeping the build script around :p. Remove the build script and I'll merge it :)

**Comment by exorcist-git** [comment]
ill do when im home :^)

**Comment by exorcist-git** [comment]
also oof i forgot to test the build script

**Comment by exorcist-git** [comment]
right so its ready...?

**Pull request merged**
